### ISSUE TITLE
What Black squares on the display

### ISSUE THREAD

**Issue by gadjet** [bigtreetech/OctoBTT#15]
Hi,
I've just gt the OctoBTT up and running and I have a small black square on the home screen just before the "-*C" text at the bottom of the screen in the centre.  Also when clicking on the control icon there is a larger square black area i the top right corner.

What are these black squares?

Thanks

**Comment by bigtreetech** [comment]
Sorry ,is my mistake, the icon adaptation exception,we will solve this problem in the net updated version.
