### ISSUE TITLE
No WIFI connection 

### ISSUE THREAD

**Issue by poooh21** [bigtreetech/OctoBTT#16]
I recently received the PI TFT50. when i connect my Raspberry PI 4 to the screen I am unable to connect to any WIFI connections. if i  unplug it from the screen, no problem connecting to my network. I have went through all the resolution settings on PI to see if that would help. no luck. do you have any suggestions on how to fix this issue?

**Comment by bigtreetech** [comment]
The same question has been answered:
https://github.com/bigtreetech/OctoBTT/issues/8
