### ISSUE TITLE
OctoBTT not starting after restart.

### ISSUE THREAD

**Issue by LittleDevil76** [bigtreetech/OctoBTT#17]
Just installed OctoBTT on a new Rass Pi 4b now, followed your guide  and after ". install.sh" is finish, i have full control of the printer
on the 5" screen.
But, after i do a restart of the Pi, the OctoBTT do not start. It just loads up to command line, and thats it.
![20201006_105130](https://user-images.githubusercontent.com/28232143/95157354-f9260380-07c2-11eb-93eb-1e2cb05144d6.jpg)

Is there something im doing wrong or what.??

**Comment by bigtreetech** [comment]
Refer to Step 4 to check that the configuration is correct.

**Comment by LittleDevil76** [comment]
Sorry, same deal. Does not start..hmm
But after i do a . install.sh , the install stops ¨freezes right here
![2020-10-07 (2)](https://user-images.githubusercontent.com/28232143/95355975-5c618400-08f0-11eb-884b-23939301836b.png)


it boots at this point and i can do whatever, but after a reboot, same deal..
Strange..!`?
![20201007_225740](https://user-images.githubusercontent.com/28232143/95356276-afd3d200-08f0-11eb-8f2e-8d48e4c8d341.jpg)

**Comment by bigtreetech** [comment]
> Sorry, same deal. Does not start..hmm
> But after i do a . install.sh , the install stops ¨freezes right here
> ![2020-10-07 (2)](https://user-images.githubusercontent.com/28232143/95355975-5c618400-08f0-11eb-884b-23939301836b.png)
> 
> it boots at this point and i can do whatever, but after a reboot, same deal..
> Strange..!`?
> ![20201007_225740](https://user-images.githubusercontent.com/28232143/95356276-afd3d200-08f0-11eb-8f2e-8d48e4c8d341.jpg)

If it is true that starting the remote interface from a command does cause the command line to freeze, you can manually restart OctoBTT from the control page of the interface to break the freeze; Do not attempt to force an exit on the remote interface, as this will cause the interface to lock and refuse to start. If you refuse to start, you can only release the lock by restarting raspberry PI.

Note: You don't need to run install.sh again, you need to refer to Step4 to configure the start parameter. If the configuration is invalid, you can print the contents of '/etc/rc.local' file configuration file through 'cat' instruction and send the screenshot to me to check whether the configuration is correct.

command usage : 
cat /etc/rc.local

**Comment by LittleDevil76** [comment]
This one`?
![2020-10-08 (1)](https://user-images.githubusercontent.com/28232143/95448652-e01d7e00-098d-11eb-9b37-2a5bb45854e3.png)

**Comment by bigtreetech** [comment]
> This one`?
> ![2020-10-08 (1)](https://user-images.githubusercontent.com/28232143/95448652-e01d7e00-098d-11eb-9b37-2a5bb45854e3.png)

Right, now I know what the problem is, your boot command is wrong, the correct command is `su -l pi -c "startx -- -nocursor"`
* **-l** (This is a "**Low**" lowercase '_L_’, not an '_I_' in "**Issue**")
* Reference images link ([https://github.com/bigtreetech/OctoBTT/blob/master/IMG/4_3_startup.png](https://github.com/bigtreetech/OctoBTT/blob/master/IMG/4_3_startup.png))
