### ISSUE TITLE
In install.sh wrong dir.

### ISSUE THREAD

**Issue by Tompudex** [bigtreetech/OctoBTT#2]
In a file;
sudo service octoprint stop
cp OctoBQPi/config.yaml .octoprint/config.yaml
sudo service octoprint start
cp OctoBQPi/.xsession .xsession
the path is incorrect.

**Comment by Minglarn** [comment]
I've tried to change to right path, but it complains about OctoBTT/.xsession is not found. 
Any solution for that?

**Comment by bigtreetech** [comment]
> In a file;
> sudo service octoprint stop
> cp OctoBQPi/config.yaml .octoprint/config.yaml
> sudo service octoprint start
> cp OctoBQPi/.xsession .xsession
> the path is incorrect.

Thank you for your feedback. I have found the problem. I am sorry for the omission of project file upload.

**Comment by bigtreetech** [comment]
> I've tried to change to right path, but it complains about OctoBTT/.xsession is not found.
> Any solution for that?

This problem is the omission of the project file upload on my side. At present, we have added the missing file. Thank you for your feedback.
