### ISSUE TITLE
Random reboots of the Pi while installing

### ISSUE THREAD

**Issue by SimonTil** [bigtreetech/OctoBTT#27]
My Raspberry Pi 3A+ randomly reboots multiple times while trying to install OctoBTT.
After first reboot I waited almost 1.5 hours, but nothing happened. It just crashed. Second till fifth reboot same, but waited shorter. Last reboot it was almost at 90%, but then reboot and could start on.
Power Supply is standard 5V/2.5A, so, nothing wrong there.
Video of the steps I took to get here:
[OctoBTT.zip](https://github.com/bigtreetech/OctoBTT/files/5683832/OctoBTT.zip)

**Comment by bigtreetech** [comment]
This look is your RaspberryPi suddenly in the process of running off electricity to restart, you can start the raspberries pie after SSH remote connection, wait for after a period of time to observe whether the SSH will automatically disconnect, if it is, may be the result of your power supply is not stable, or you could be there to install network connection in the process of slowly over time lead to an early end script automatically restart; Network connection is generally reflected in the installation process to download a longer stay will.
