### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by gfenglo** [bigtreetech/OctoBTT#29]
octobtt high cpu usage in idle. around 40% in idle

**Comment by bigtreetech** [comment]
The CPU performance loss is normal, which is required by OctoBTT for continuous interface interaction to obtain accurate operating status, and the subsequent performance optimization will continue.

**Comment by gfenglo** [comment]
Compared to touch UI, Octodash, and Octoscreen. They use less than 10% CPI usage in idle.

**Comment by bigtreetech** [comment]
By contrast, our UI improves the user experience by sacrificing performance. Of course, such a large performance gap is related to the software architecture design we take, so we will improve the actual operation efficiency in the subsequent upgrades, so as to optimize the transition loss on performance.

**Comment by gfenglo** [comment]
Are you going to send me another board, or do I have to buy another board?

**Comment by gfenglo** [comment]
Sorry, wrong reply.

**Comment by bigtreetech** [comment]
Hello, I have solved the problem of excessive CPU occupation. At present, as long as the UI does not stay on the camera monitoring page, there will not be a large load on CPU. Compared with the previous version, the current CPU optimization only takes up 10% of the previous one. If no new questions come up within a week, I will close the current topic.

**Comment by gfenglo** [comment]
Sorry, I give up on OctoBTT.

**Comment by bigtreetech** [comment]
Sorry to let you down due to my mistake and delay. If you want to try our OCTOBTT at some point in the future, I will do my best to help you use it.
