### ISSUE TITLE
Wifi doesn't work when screen is connected

### ISSUE THREAD

**Issue by NovaViper** [bigtreetech/OctoBTT#30]
I just got my screen yesterday, and all day, I've been trying to get this wifi on both of my raspberry Pi 3B+ and 4B 2GB working with the screen attached. Whenever the screen is plugged in, the wifi just stops working entirely. I have reflashed the pis multiple times, only ever getting them to connect once before the issue came back again. This is really frustrating 

--Update--
Just discovered that the screen itself is causing interference with the wifi antenna when mounted like so
![image](https://user-images.githubusercontent.com/7191115/110354926-4de1da80-7ffe-11eb-9ee3-9db780977c7d.png)
Clearly a major design flaw.. this seriously needs to be fixed because I ended up buying another pi thinking my original one had something defective on it

**Comment by bigtreetech** [comment]
Please consult the screen after-sales service for this problem, thank you.
