### ISSUE TITLE
OctoBTT connection to BiQu BX printer

### ISSUE THREAD

**Issue by wolfgangdecker** [bigtreetech/OctoBTT#32]
I received one of the production models and attached a Raspberry Pi Model 3 B+ to the main board. I only seem to get connection to the printer functions if I run a USB cable from the Pi to the front USB port in the printer. In the previews published on YouTube (e.g. by Teaching Tech) it seems that the Pi would connect directly with the printer through the internal serial port. 

What is the problem with my model?

**Comment by bigtreetech** [comment]
Thank you for your careful discovery. We cannot completely guarantee that there are no mistakes, but we will learn lessons and correct the known mistakes in time.

**Comment by bigtreetech** [comment]
The video shows the earlier version of the development, in the current version of the development can be implemented through the Octo BTT screen to Octoprint to achieve the basic function of the operation; On the BX machine, our machine is not connected to Raspberry Pi through serial port, but directly connected to Raspberry Pi through microUSB or Type C port of the host machine, while Octo BTT will automatically realize the automatic docking between Octoprint and the machine.

**Comment by wolfgangdecker** [comment]
Thank you for getting back, appreciate the answer. It is a little ambiguous, though. 

To clarify I have attached two pictures:
![Inked20210413_103209_LI](https://user-images.githubusercontent.com/12385432/114589388-3b863c80-9c4d-11eb-8d4e-24bf32e43eb4.jpg)
![Inked20210413_103249_LI](https://user-images.githubusercontent.com/12385432/114589450-493bc200-9c4d-11eb-9b64-9fdba012b8b4.jpg)

I had to connect the machine through a USB cable as shown by the yellow circled connections, otherwise OctoBTT does not establish a connection with the printer. You are saying, however, that this should be possible by the connection as shown in the red circle, which is the direct connection with the host machine, which also bring OctoBTT on the screen?

If I only connect as shown in the red circle, OctoBTT is not able to read data from the printer, only if I connect via the connection in the yellow circle. 

Please clarify.

Thank you.

W.

**Comment by bigtreetech** [comment]
The connection mode shown in the figure is correct. The red part of the connection cable provides touch input device for the interface of Raspberry Pi, while the yellow part of the connection cable provides connection with the motherboard for Raspberry Pi. Therefore, if Raspberry Pi needs to connect to the motherboard, the yellow part of the connection cable must be installed.

**Comment by wolfgangdecker** [comment]
Thank you for the clarification. This was not included in the setup manual, so maybe it should be added.

**Comment by bigtreetech** [comment]
Yes, we found that we did have this omission, so we corrected it in the subsequent installation manual of the product. Thank you for your feedback.
