### ISSUE TITLE
a non issue misspell Cencal instead of Cancel?

### ISSUE THREAD

**Issue by rlmarin** [bigtreetech/OctoBTT#34]
a non issue misspell that bugs I guess just me lol 
When ever I need to Cancel out I Laughed a bit at this misspell not sure if its intentional 

https://imgur.com/pQjV3kr

**Comment by bigtreetech** [comment]
Thank you for your careful discovery. We cannot completely guarantee that there are no mistakes, but we will learn lessons and correct the known mistakes in time.
