### ISSUE TITLE
I can't install OctoBTT

### ISSUE THREAD

**Issue by cmicheli346** [bigtreetech/OctoBTT#35]
hello, I don't know raspberry pi and following the guide to install OctoBTT I was stuck as shown in the image, could someone explain me how to solve? thank you
![Immagine 2021-04-11 180321](https://user-images.githubusercontent.com/70413820/114311745-3e1f4f80-9af0-11eb-82b0-66b644f24b40.jpg)

**Comment by predy3dprint** [comment]
Firstly try : "sudo apt-get update" (without the quotation mark).

**Comment by cmicheli346** [comment]
hi, thanks for the reply.
I did what you suggested and then tried to install again .... same result as before or almost. Only the line changes
![update](https://user-images.githubusercontent.com/70413820/114313558-46c75400-9af7-11eb-9847-64a152e704d6.jpg)

**Comment by predy3dprint** [comment]
Hmm... It seems that some repos are not reachable. Especially the QT- Stuff. Is your raspi connected with the internet?
![image](https://user-images.githubusercontent.com/79607312/114315484-75e1c380-9aff-11eb-9a2c-c8607d741239.jpeg)

**Comment by cmicheli346** [comment]
yes, first with wifi, now with the ethernet cable

**Comment by predy3dprint** [comment]
Sorry. But I found only the following instructions: 

https://awesomeopensource.com/project/bigtreetech/OctoBTT

May be useful for you.

**Comment by cmicheli346** [comment]
yes, they are the same ones that I followed

**Comment by bigtreetech** [comment]
It looks like the problem is caused by network instability. When you install on a wireless network, you may encounter a failure caused by network instability. At this time, it is recommended that you switch to a wired network for installation.

**Comment by cmicheli346** [comment]
ok, the first time i tried to install everything with wifi but after i connected the cable and the problem continues. How can I go about trying to re-download everything? now if I try it tells me that install.sh already exists but if I try to launch it it gives me that error in the end also connected via cable

**Comment by cmicheli346** [comment]
no solution ... should I trash everything? it all seems so easy to see the tutorials but I have been stuck for weeks

**Comment by bigtreetech** [comment]
It is recommended that you reinstall according to README, because the previous installation failure caused the loss of part of the file may lead to repeated Settings and other problems, so when you run again after the failure of the operation may trigger a second rejection operation, if there is still a failure, you can contact me by email.

E-mail: [developer01@biqu3d.com](developer01@biqu3d.com)
