### ISSUE TITLE
What does the "Ban" icon refer to

### ISSUE THREAD

**Issue by anupchavda1** [bigtreetech/OctoBTT#6]
I'm a newb when it comes to programming/coding, but i had a look at the c++ code and noticed that the word "BAN" related to something to do with the Filament...But the word does not make sense in this context. looking further it looks like its the connection / printer status.

can we get a more appropriate label for the status rather than the word "BAN"?

Thanks

**Comment by Shine6Z** [comment]
Ok, I will choose a more reasonable display to display the place, for now I just think this icon is used to remind the user that it cannot be operated or not recommended.

**Comment by bigtreetech** [comment]
A new version has been released and I have changed the Busy" Ban" display status to "Busy". Thanks for your feedback.
